# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtWidgets
from DBCat.hosts import host_info


class HostEditDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super(HostEditDialog, self).__init__(parent)
        self.id = ''
        self.setupUi(self)

    def get_host(self):
        return host_info.HostInfo(self.id, self.name.text(), self.host.text(), self.port.text(), self.userName.text(),
                                 self.password.text(), self.type.text(), self.env.currentText())

    def init_with_host(self, host):
        print('init dialog with host:{}'.format(host.to_json()))
        self.id = host.id
        self.name.setText(host.name)
        self.host.setText(host.host)
        self.port.setText(host.port)
        self.userName.setText(host.user_name)
        self.password.setText(host.password)
        self.type.setText(host.type)
        self.env.setCurrentText(host.environment)

    def save(self):
        self.accept()

    def cancel(self):
        self.reject()

    def setupUi(self, HostEditDialog):
        HostEditDialog.setObjectName("NewHost")
        HostEditDialog.resize(304, 274)
        self.verticalLayout = QtWidgets.QVBoxLayout(HostEditDialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(HostEditDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(HostEditDialog)
        self.name.setMinimumSize(QtCore.QSize(0, 26))
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(HostEditDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.host = QtWidgets.QLineEdit(HostEditDialog)
        self.host.setMinimumSize(QtCore.QSize(0, 26))
        self.host.setObjectName("host")
        self.gridLayout.addWidget(self.host, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(HostEditDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.port = QtWidgets.QLineEdit(HostEditDialog)
        self.port.setMinimumSize(QtCore.QSize(0, 26))
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(HostEditDialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.userName = QtWidgets.QLineEdit(HostEditDialog)
        self.userName.setMinimumSize(QtCore.QSize(0, 26))
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(HostEditDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(HostEditDialog)
        self.password.setMinimumSize(QtCore.QSize(0, 26))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(HostEditDialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.type = QtWidgets.QLineEdit(HostEditDialog)
        self.type.setEnabled(False)
        self.type.setMinimumSize(QtCore.QSize(0, 26))
        self.type.setObjectName("type")
        self.gridLayout.addWidget(self.type, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(HostEditDialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.env = QtWidgets.QComboBox(HostEditDialog)
        self.env.setMinimumSize(QtCore.QSize(0, 26))
        self.env.setObjectName("env")
        self.gridLayout.addWidget(self.env, 6, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonOk = QtWidgets.QPushButton(HostEditDialog)
        self.pushButtonOk.setMinimumSize(QtCore.QSize(58, 34))
        self.pushButtonOk.setMaximumSize(QtCore.QSize(58, 34))
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout_2.addWidget(self.pushButtonOk)
        self.pushButtonCancel = QtWidgets.QPushButton(HostEditDialog)
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(58, 34))
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(58, 34))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.setWindowTitle("数据库连接编辑")
        self.label_2.setText("连接名称:")
        self.name.setText("新建连接")
        self.label_3.setText("Host地址:")
        self.host.setText("localhost")
        self.label_4.setText("端口:")
        self.port.setText("3306")
        self.label_5.setText("用户名:")
        self.userName.setText("root")
        self.label_6.setText("密码:")
        self.label_7.setText("数据库:")
        self.label_8.setText("环境:")
        self.pushButtonOk.setText("保存")
        self.pushButtonCancel.setText("取消")

        self.type.setText("mysql")
        self.env.addItem('测试')
        self.env.addItem('生产')

        QtCore.QMetaObject.connectSlotsByName(HostEditDialog)
        self.pushButtonOk.clicked.connect(self.save)
        self.pushButtonCancel.clicked.connect(self.cancel)
